INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (1, 1, 'guitare');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (1, 2, 'guitare');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (2, 2, 'guitare, chant');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (3, 2, 'basse');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (4, 2, 'batterie');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (5, 2, 'chant');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (6, 2, 'claviers');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (7, 1, 'guitare');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (8, 1, 'batterie');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (9, 1, 'basse');
INSERT INTO public.plays_with (plays_with_member_id, plays_with_band_id, plays_with_instrument) VALUES (10, 1, 'chant');