INSERT INTO public.styles (style_id, style_name) VALUES (1, 'Rock');
INSERT INTO public.styles (style_id, style_name) VALUES (2, 'Jazz');
INSERT INTO public.styles (style_id, style_name) VALUES (3, 'Pop');
INSERT INTO public.styles (style_id, style_name) VALUES (4, 'Death Brutal');
INSERT INTO public.styles (style_id, style_name) VALUES (5, 'Black Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (6, 'Post-Black Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (7, 'Heavy Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (8, 'Folk-Pop');
INSERT INTO public.styles (style_id, style_name) VALUES (9, 'Rap');
INSERT INTO public.styles (style_id, style_name) VALUES (10, 'Hip-Hop');
INSERT INTO public.styles (style_id, style_name) VALUES (11, 'Techno');
INSERT INTO public.styles (style_id, style_name) VALUES (12, 'Deathcore');
INSERT INTO public.styles (style_id, style_name) VALUES (13, 'Blues');
INSERT INTO public.styles (style_id, style_name) VALUES (14, 'Death Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (15, 'Metal Alternatif');
INSERT INTO public.styles (style_id, style_name) VALUES (16, 'Thrash Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (17, 'Funk');
INSERT INTO public.styles (style_id, style_name) VALUES (18, 'Punk');
INSERT INTO public.styles (style_id, style_name) VALUES (19, 'Death Technique');
INSERT INTO public.styles (style_id, style_name) VALUES (20, 'Grindcore');
INSERT INTO public.styles (style_id, style_name) VALUES (21, 'Musique Traditionnelle');
INSERT INTO public.styles (style_id, style_name) VALUES (22, 'Folk');
INSERT INTO public.styles (style_id, style_name) VALUES (23, 'Death Black Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (24, 'Death Mélodique');
INSERT INTO public.styles (style_id, style_name) VALUES (25, 'Néo Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (26, 'Death Progressif');
INSERT INTO public.styles (style_id, style_name) VALUES (27, 'Rock Progressif');
INSERT INTO public.styles (style_id, style_name) VALUES (28, 'Metal Progressif');
INSERT INTO public.styles (style_id, style_name) VALUES (29, 'Stoner');
INSERT INTO public.styles (style_id, style_name) VALUES (30, 'Sludge');
INSERT INTO public.styles (style_id, style_name) VALUES (31, 'Reggae');
INSERT INTO public.styles (style_id, style_name) VALUES (32, 'Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (33, 'Hard Rock');
INSERT INTO public.styles (style_id, style_name) VALUES (34, 'Metal Symphonique');
INSERT INTO public.styles (style_id, style_name) VALUES (35, 'Black Death Metal');
INSERT INTO public.styles (style_id, style_name) VALUES (36, 'Soul');
INSERT INTO public.styles (style_id, style_name) VALUES (37, 'Jazz fusion');