INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (1, 'Discerner', 1, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (2, 'Abysses', 2, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (3, 'L''Inconnue, part I', 3, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (4, 'L''Inconnue, part II', 4, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (5, 'Opprobre', 5, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (6, 'Sensitive', 6, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (7, 'Danse Catatonique', 7, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (8, 'Intro', 1, 53);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (9, 'Encounter with the Doppelganger', 2, 216);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (10, 'Body Cell', 3, 208);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (11, 'Helter Skelter', 4, 196);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (12, 'Aera Dementiae', 5, 343);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (13, 'Paranoid Visions (Part. 2)', 6, 235);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (14, 'The Other Me', 7, 158);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (15, 'God ov Fire', 8, 202);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (16, 'Voices', 9, 238);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (17, 'Insania Lupina', 10, 267);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (18, 'Intro', 1, 59);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (19, 'Hundred Eyes', 2, 199);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (20, 'Ghost in the Closet', 3, 194);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (21, 'Arachno', 4, 195);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (22, 'My Darkest Hour', 5, 217);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (23, 'Diabolus Ex Machina', 6, 217);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (24, 'Wrinkled Skin', 7, 175);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (25, 'One More Second', 8, 230);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (26, 'Panic Room', 9, 219);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (27, 'Burnt Alive', 10, 213);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (28, 'Nightfall Thoughts', 11, 105);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (29, 'Paranoid Visions (Part I)', 12, 255);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (30, 'Cannibal Way of Life', 1, 221);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (31, 'Paranoid Visions (Part II)', 2, 236);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (32, 'Bloodred Honeymoon', 3, 181);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (33, 'Psychopatia Sexualis', 4, 180);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (34, 'Terra', 1, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (35, 'Aeon', 2, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (36, 'Guma', 3, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (37, 'Oceans Deep', 4, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (38, 'Resilient', 5, null);
INSERT INTO public.songs (song_id, song_name, song_track_number, song_length) VALUES (39, 'The Angry Octopus', 6, null);